version: '3'
services:
    # shopeetax:
    #       build: './app/'
    #       expose:
    #         - '9090'
    #       command: 'make docker-run'
    #       ports:
    #         - '9091:9090'
    #       depends_on:
    #         - mysqldb
    #       networks:
    #         - shopeetaxnet
    mysqldb:
      image: mysql:5.7
      env_file: .env
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "9096:3306"
      volumes:
        - ./db/:/docker-entrypoint-initdb.d
        # - ${MYSQL_PERSISTENT_VOL}:/var/lib/mysql
      networks:
        - shopeetaxnet
networks:
    shopeetaxnet:
